<?php

namespace Bidhee\NewsBundle\Repository;

/**
 * NewsMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsMetaRepository extends \Doctrine\ORM\EntityRepository
{
}
