<?php

namespace Bidhee\NewsBundle\Repository;

/**
 * NewsReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsReviewRepository extends \Doctrine\ORM\EntityRepository
{

}
