parameters:
    database_host:    localhost
    database_port:
    database_name:     db_janata
    database_user:     root
    database_password:
    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~
    secret:            ThisTokenIsNotSoSecretChangeIt
    per_page_limit: 20
    admin_dir_mask: janatasecure
