parameters:
    database_host:     128.199.89.47
    database_port:     3306
    database_name:     db_janata
    database_user:     root
    database_password: Bidhee98010
    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~
    secret:            ThisTokenIsNotSoSecretChangeIt
    per_page_limit: 20
    admin_dir_mask: janatasecure
