<?php

namespace Bidhee\ContentBundle\Repository;

use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAll($offset, $perPage, $filters)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('c')
            ->from('BidheeContentBundle:Content', 'c')
            ->where('1 = 1');

        if (is_array($filters) && !empty($filters)) {
            if (array_key_exists('title', $filters) && $filters['title'] != '') {
                $qb->andWhere('c.title = :title')
                    ->setParameter('title', $filters['title']);
            }
        }

        $qb->orderBy('c.createdOn', 'desc');

        $adapter = new DoctrineORMAdapter($qb);
        $pagerfanta = new Pagerfanta($adapter);
        $pagerfanta->setMaxPerPage($perPage);
        $pagerfanta->setCurrentPage($offset);

        return $pagerfanta;
    }
}
