<?php

namespace Bidhee\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Bidhee\UserBundle\Entity\Author;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{

    public function getAuthorListQuery($filters)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('a')
            ->from(Author::class, 'a')
            ->where('1=1');

        if (array_key_exists('name', $filters) and $filters['name'] != '') {
            $qb->andWhere('a.name LIKE :name')->setParameter('name', '%' . $filters['name'] . '%');
        }

        if (array_key_exists('username', $filters) and $filters['username'] != '') {
            $qb->andWhere('a.username LIKE :username')->setParameter('username', '%' . $filters['username'] . '%');
        }

        if (array_key_exists('email', $filters) and $filters['email'] != '') {
            $qb->andWhere('a.email LIKE :email')->setParameter('email', '%' . $filters['email'] . '%');
        }

        $qb->orderBy('a.createdOn', 'DESC');

        return $qb->getQuery();
    }
}
