<?php

namespace Bidhee\UserBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Bidhee\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{



    public function getAuthors( $activeOnly = true )
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('u')
            ->from(User::class, 'u')
            ->where('u.roles LIKE :role')
            ->setParameter('role', '%ROLE_AUTHOR%')
        ;

        if( $activeOnly )
        {
            $qb->andWhere('u.enabled = 1');
        }

        $qb->orderBy('u.name', 'ASC');

        return $qb->getQuery()->getResult();
    }

}
