<?php

namespace Bidhee\EpaperBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Bidhee\EpaperBundle\Entity\Epaper;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpaperRepository extends EntityRepository
{

    public function getEpaperListQuery($filters)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('a')
            ->from(Epaper::class, 'a')
            ->where('1=1');

        if (array_key_exists('title', $filters) and $filters['title'] != '') {
            $qb->andWhere('a.title LIKE :title')->setParameter('title', '%' . $filters['title'] . '%');
        }

        $qb->orderBy('a.createdOn', 'DESC');

        return $qb->getQuery();
    }
}
