<?php

namespace Bidhee\AdBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AdTypeController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Bidhee\AdBundle\Controller\AdTypeController();
        return $instance;
    }
}
