<?php

namespace Bidhee\EpaperBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class EpaperController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Bidhee\EpaperBundle\Controller\EpaperController();
        return $instance;
    }
}
