<?php

namespace Bidhee\ContentBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ContentController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Bidhee\ContentBundle\Controller\ContentController();
        return $instance;
    }
}
