<?php

namespace Bidhee\FeedBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class InstantArticleFeedController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Bidhee\FeedBundle\Controller\InstantArticleFeedController();
        return $instance;
    }
}
