<?php

namespace Bidhee\NewsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AjaxController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Bidhee\NewsBundle\Controller\AjaxController();
        return $instance;
    }
}
