<?php

namespace Dmishh\Bundle\SettingsBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SettingsController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Dmishh\Bundle\SettingsBundle\Controller\SettingsController();
        return $instance;
    }
}
