<?php

namespace FM\ElfinderBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ElFinderController__JMSInjector
{
    public static function inject($container) {
        $instance = new \FM\ElfinderBundle\Controller\ElFinderController();
        return $instance;
    }
}
